### ISSUE TITLE
AttachmentType.TXT - NoClassDefFound

### ISSUE THREAD

**Issue by sergei-zh** [allure-framework/allure-core#260]
After upgrading from 1.3.2 to 1.3.9:

Code like:

```
@Step
@Attach(type = AttachmentType.TXT)
public String logUrl() {
    return driver.getCurrentUrl();
}
```

Causes an exception like:

java.lang.NoClassDefFoundError: org/apache/commons/io/Charsets
    at ru.yandex.qatools.allure.utils.AllureResultsUtils.writeAttachment(AllureResultsUtils.java:95)
    at ru.yandex.qatools.allure.utils.AllureResultsUtils.writeAttachment(AllureResultsUtils.java:86)
    at ru.yandex.qatools.allure.events.MakeAttachEvent.process(MakeAttachEvent.java:25)
    at ru.yandex.qatools.allure.events.MakeAttachEvent.process(MakeAttachEvent.java:13)
    at ru.yandex.qatools.allure.Allure.fire(Allure.java:54)
    at ru.yandex.qatools.allure.aspects.AllureAttachAspects.attach(AllureAttachAspects.java:35)
......
